### ISSUE TITLE
What dothe "name" field in "attribute" mean? It seems not match in CN dataset.

### ISSUE THREAD

**Issue by Desein-Yang** [nuochenpku/Harry-Potter-Dialogue-Dataset#1]
![image](https://user-images.githubusercontent.com/17928873/202952394-5b5ae2a2-55d9-4709-96ff-c335c40ef019.png)

**Comment by nuochenpku** [comment]
This issue happeded in which json file? It could be mistake in the data-processing. I will modify this as soon as possible!

**Comment by nuochenpku** [comment]
We have fixed this mistake and updated the new executable file. Thanks for your comment!

**Comment by Desein-Yang** [comment]
> We have fixed this mistake and updated the new executable file. Thanks for your comment!

Thanks
