### ISSUE TITLE
Can't download dataset(en)

### ISSUE THREAD

**Issue by dongbingfeng** [nuochenpku/Harry-Potter-Dialogue-Dataset#2]
It seems the dataset(en) downloader file is deleted by google drive:
https://drive.google.com/file/d/1cuoYGpEcux81gHXmmtm2RmZuyHpGCULm/view?usp=share_link
Could you please put a new link? Thanks.

**Comment by nuochenpku** [comment]
How about this one: https://drive.google.com/file/d/187ywZegc1YICDLR7snc-PsOLMHbLhNRP/view?usp=sharing

**Comment by dongbingfeng** [comment]
It works! Thanks very much~
________________________________
发件人: Jerry Chen ***@***.***>
发送时间: 2023年4月21日 13:35
收件人: nuochenpku/Harry-Potter-Dialogue-Dataset ***@***.***>
抄送: dongbingfeng ***@***.***>; Author ***@***.***>
主题: Re: [nuochenpku/Harry-Potter-Dialogue-Dataset] Can't download dataset(en) (Issue #2)


How about this one: https://drive.google.com/file/d/187ywZegc1YICDLR7snc-PsOLMHbLhNRP/view?usp=sharing

―
