### ISSUE TITLE
what is the file save path?

### ISSUE THREAD

**Issue by Rogerspy** [nuochenpku/Harry-Potter-Dialogue-Dataset#3]
I can not find the downloaded json file after running `download.exe`.

**Comment by nuochenpku** [comment]
Thanks for your interests in our work.  We are utilizing GPT-4 to polish our datasets and revise some mistakes which could take several days.  We will release the new version of our datasets as soon as possible.

**Comment by nuochenpku** [comment]
Now you can directly download the data from our new official website: https://nuochenpku.github.io/HPD.github.io/

**Comment by Rogerspy** [comment]
> Now you can directly download the data from our new official website: https://nuochenpku.github.io/HPD.github.io/

Thank you
