### ISSUE TITLE
Should we just use the train file?

### ISSUE THREAD

**Issue by liyucheng09** [nuochenpku/Harry-Potter-Dialogue-Dataset#4]
Nice job for the dataset! A simple question.

In `en_train_set.json`, there is scenes, dialogues, and attributes. So basically everything's there. Does that mean we can just use the traing file as all data (attributes, relations etc.) are all put in the train file?

**Comment by nuochenpku** [comment]
Thanks for your question.

Indeed, train file includes all useful information for training!
